/**************************************************************************************************************************************************
*                                 Copyright © 2012 Texas Instruments Incorporated - http://www.ti.com/                                            *
***************************************************************************************************************************************************
*  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: *
*                                                                                                                                                 *
*    Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                 *
*                                                                                                                                                 *
*    Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the        *
*    documentation and/or other materials provided with the distribution.                                                                         *
*                                                                                                                                                 *
*    Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived      *
*    from this software without specific prior written permission.                                                                                *
*                                                                                                                                                 *
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT          *
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT     *
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT         *
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY    *
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE      *
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                                                                           *
***************************************************************************************************************************************************/
/* Autogenerated header file for flash configuration data */
#ifndef _CFG_MAP
#define _CFG_MAP

#ifdef __cplusplus
extern "C" {
#endif

#define BITSTREAM_START_ADDR         0x00000000
#define BITSTREAM_SIZE               0x00040000

#define WPC_FW_0_START_ADDR          0x00040000
#define WPC_FW_0_SIZE                0x00000ce8

#define SEQUENCE_0_START_ADDR        0x00044000
#define SEQUENCE_0_SIZE              0x00001000

#define SEQUENCE_1_START_ADDR        0x00045000
#define SEQUENCE_1_SIZE              0x00000d10

#define SEQUENCE_2_START_ADDR        0x00046000
#define SEQUENCE_2_SIZE              0x00000d10

#define SEQUENCE_3_START_ADDR        0x00047000
#define SEQUENCE_3_SIZE              0x00000d10

#define SEQUENCE_4_START_ADDR        0x00048000
#define SEQUENCE_4_SIZE              0x00000d10

#define SEQUENCE_5_START_ADDR        0x00049000
#define SEQUENCE_5_SIZE              0x00000d10

#define SEQUENCE_6_START_ADDR        0x0004a000
#define SEQUENCE_6_SIZE              0x00000d10

#define CMT_LUT_0_START_ADDR         0x0004b200
#define CMT_LUT_0_SIZE               0x00000600

#define CMT_LUT_1_START_ADDR         0x0004b800
#define CMT_LUT_1_SIZE               0x00000600

#define CMT_LUT_2_START_ADDR         0x0004be00
#define CMT_LUT_2_SIZE               0x00000600

#define CMT_LUT_3_START_ADDR         0x0004c400
#define CMT_LUT_3_SIZE               0x00000600

#define CMT_LUT_4_START_ADDR         0x0004ca00
#define CMT_LUT_4_SIZE               0x00000600

#define CMT_LUT_5_START_ADDR         0x0004d000
#define CMT_LUT_5_SIZE               0x00000600

#define CMT_LUT_6_START_ADDR         0x0004d600
#define CMT_LUT_6_SIZE               0x00000600

#define DRC_TABLE_0_START_ADDR       0x0004dc00
#define DRC_TABLE_0_SIZE             0x00000100

#define SPLASH_0_START_ADDR          0x00063000
#define SPLASH_0_SIZE                0x00033000

#define SEQUENCE_7_START_ADDR        0x00080000
#define SEQUENCE_7_SIZE              0x00000d10

#define SEQUENCE_8_START_ADDR        0x00081800
#define SEQUENCE_8_SIZE              0x00000d10

#define SEQUENCE_9_START_ADDR        0x00083000
#define SEQUENCE_9_SIZE              0x00000d10

#define CMT_LUT_7_START_ADDR         0x0008e000
#define CMT_LUT_7_SIZE               0x00000600

#define CMT_LUT_8_START_ADDR         0x0008e800
#define CMT_LUT_8_SIZE               0x00000600

#define CMT_LUT_9_START_ADDR         0x0008f000
#define CMT_LUT_9_SIZE               0x00000600

#define SPLASH_1_START_ADDR          0x00096000
#define SPLASH_1_SIZE                0x00033000

#define SPLASH_2_START_ADDR          0x000c9000
#define SPLASH_2_SIZE                0x00033000

#define SPLASH_3_START_ADDR          0x000FC000
#define SPLASH_3_SIZE                0x00033000

#define OPT_SPLASH_0_START_ADDR      0x00134000
#define OPT_SPLASH_0_SIZE            0x000cb100

#ifdef __cplusplus
}
#endif

#endif
